### ISSUE TITLE
[bug] failed to parse input

### ISSUE THREAD

**Issue by pexcn** [dywisor/ip-dedup#1]
Hi dywisor:

I seem to find a bug in ip-dedup, I did the following:
```bash
mkdir test && cd test

# build
git clone https://github.com/dywisor/ip-dedup.git && cd ip-dedup
make STANDALONE=1 CFLAGS_EXTRA="-s -Wl,--build-id=none"

cd ..

# get ipv6 cidr
curl -sSL https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest | grep ipv6 | grep TW | awk -F\| '{ printf("%s/%d\n", $4, $5) }' > ip6-cidr.txt

# test...
ip-dedup/obj/ip-dedup -6 < ip6-cidr.txt > output-1.txt    # it's work
ip-dedup/obj/ip-dedup -6 ip6-cidr.txt > output-2.txt      # it's work
ip-dedup/obj/ip-dedup -6 < ip6-cidr.txt -o output-3.txt   # it's work
ip-dedup/obj/ip-dedup -6 ip6-cidr.txt -o output-4.txt     # not work
Error: failed to parse input
```

The test 4 cannot parse input.

**Comment by pexcn** [comment]
Oh sorry... my bad, my usage is wrong.
that will work:
```bash
ip-dedup/obj/ip-dedup -6 -o t4 ip6-cidr.txt
```

**Comment by dywisor** [comment]
@pexcn 
That's a BSD<>GNU limitation in getopt(), options (``-4``) can only appear before any positional argument (``ip6-cidr.txt``).

If you'd like to mix&match as in test 4, you can now do this with the ``USE_LONGOPT=1`` build-time flag (as of version 0.6 / commit e6feb0b18b780f7727c32d028d93cbf670989c18). The newly introduced long option names are not final yet, though.

**Comment by pexcn** [comment]
Awesome thank you 👍
